languageCode = "en"
languageName = "English"
weight = 1
title = "Robby Lawrence"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Personal website of Robby Lawrence"

[params.author]
  name = "Robby Lawrence"
  image = "img/robby.jpeg"
  headline = "Math & Optimization"
  bio = "Living, laughing, coding"
  links = [
    { github = "https://github.com/robbylawrence" },
    { linkedin = "https://www.linkedin.com/in/robert-lawrence-33b1002b8/" },
    { instagram = "https://www.instagram.com/robertwesleylawrence3" },
  ]
